//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class preferencia
    {
        public int id_preferencias { get; set; }
        public string preferencias { get; set; }
    }
}
